version: '2'
services:
  iclinic-mysql:
    build:
      context: ./
      dockerfile: docker/mysql-dockerfile
    image: "iclinic-mysql:1.0.0"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpwd
      - MYSQL_USER=iclinic
      - MYSQL_PASSWORD=iclinic
      - MYSQL_DATABASE=iclinic
    ports:
      - "3306:3306"
    container_name: iclinic-mysql